# H2 config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_x_brain
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
# API config
api:
  prefix: /api/v1
